/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    authors: Author;
    topics: Topic;
    series: Series;
    teachings: Teaching;
    resources: Resource;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    topics: TopicsSelect<false> | TopicsSelect<true>;
    series: SeriesSelect<false> | SeriesSelect<true>;
    teachings: TeachingsSelect<false> | TeachingsSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('es' | 'en') | ('es' | 'en')[];
  globals: {};
  globalsSelect: {};
  locale: 'es' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  migrationKey?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    social?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * Se genera automáticamente. Cambiarlo después de publicar creará una redirección permanente.
   */
  slug: string;
  bio?: string | null;
  /**
   * Ayuda a identificar al autor en los datos estructurados.
   */
  profileUrl?: string | null;
  image?: (number | null) | Media;
  migrationKey?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics".
 */
export interface Topic {
  id: number;
  name: string;
  /**
   * Se genera automáticamente. Cambiarlo después de publicar creará una redirección permanente.
   */
  slug: string;
  migrationKey?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "series".
 */
export interface Series {
  id: number;
  title: string;
  /**
   * Se genera automáticamente. Cambiarlo después de publicar creará una redirección permanente.
   */
  slug: string;
  kind: 'series' | 'event';
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * Completa solo lo que necesite diferir del contenido principal. El sitio genera canonical, Open Graph y datos estructurados automáticamente.
   */
  seo?: {
    /**
     * Opcional. Si se deja vacío se usa el título principal.
     */
    title?: string | null;
    /**
     * Describe con claridad el contenido. Si se deja vacío se usa el resumen.
     */
    description?: string | null;
    canonical?: string | null;
    /**
     * Úsalo solo para contenido privado, duplicado o temporal.
     */
    noIndex?: boolean | null;
    socialImage?: (number | null) | Media;
  };
  /**
   * Al guardar se creará una redirección permanente desde la URL anterior.
   */
  confirmSlugChange?: boolean | null;
  translationAutoGenerated?: boolean | null;
  migrationKey?: string | null;
  sourceUpdatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teachings".
 */
export interface Teaching {
  id: number;
  title: string;
  /**
   * Una introducción breve para tarjetas, buscadores y redes sociales.
   */
  excerpt?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  teachingDate?: string | null;
  series: number | Series;
  episode?: number | null;
  author?: (number | null) | Author;
  keyVerse?: string | null;
  /**
   * Usa pocos temas consistentes para mejorar navegación y búsqueda.
   */
  topics?: (number | Topic)[] | null;
  format?: ('video' | 'audio' | 'mixed' | 'text') | null;
  durationMinutes?: number | null;
  /**
   * Pega el enlace completo del video.
   */
  youtubeUrl?: string | null;
  /**
   * Pega el enlace completo del episodio.
   */
  applePodcastsUrl?: string | null;
  image?: (number | null) | Media;
  mediaLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  /**
   * Se genera automáticamente. Cambiarlo después de publicar creará una redirección permanente.
   */
  slug: string;
  /**
   * Completa solo lo que necesite diferir del contenido principal. El sitio genera canonical, Open Graph y datos estructurados automáticamente.
   */
  seo?: {
    /**
     * Opcional. Si se deja vacío se usa el título principal.
     */
    title?: string | null;
    /**
     * Describe con claridad el contenido. Si se deja vacío se usa el resumen.
     */
    description?: string | null;
    canonical?: string | null;
    /**
     * Úsalo solo para contenido privado, duplicado o temporal.
     */
    noIndex?: boolean | null;
    socialImage?: (number | null) | Media;
  };
  /**
   * Al guardar se creará una redirección permanente desde la URL anterior.
   */
  confirmSlugChange?: boolean | null;
  legacy?: boolean | null;
  notionPageId?: string | null;
  notionUrl?: string | null;
  syncStatus?: ('pending' | 'synced' | 'conflict' | 'error') | null;
  lastSyncedAt?: string | null;
  lastSyncSource?: ('notion' | 'payload') | null;
  syncError?: string | null;
  translationAutoGenerated?: boolean | null;
  migrationKey?: string | null;
  sourceUpdatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  title: string;
  /**
   * Una introducción breve para tarjetas, buscadores y redes sociales.
   */
  excerpt?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  contentDate?: string | null;
  kind: 'article' | 'pillar';
  author?: (number | null) | Author;
  /**
   * Usa pocos temas consistentes para mejorar navegación y búsqueda.
   */
  topics?: (number | Topic)[] | null;
  relatedTeachings?: (number | Teaching)[] | null;
  /**
   * La biblioteca solicita texto alternativo y genera versiones para tarjeta y redes.
   */
  image?: (number | null) | Media;
  featured?: boolean | null;
  /**
   * Se genera automáticamente. Cambiarlo después de publicar creará una redirección permanente.
   */
  slug: string;
  /**
   * Completa solo lo que necesite diferir del contenido principal. El sitio genera canonical, Open Graph y datos estructurados automáticamente.
   */
  seo?: {
    /**
     * Opcional. Si se deja vacío se usa el título principal.
     */
    title?: string | null;
    /**
     * Describe con claridad el contenido. Si se deja vacío se usa el resumen.
     */
    description?: string | null;
    canonical?: string | null;
    /**
     * Úsalo solo para contenido privado, duplicado o temporal.
     */
    noIndex?: boolean | null;
    socialImage?: (number | null) | Media;
  };
  /**
   * Al guardar se creará una redirección permanente desde la URL anterior.
   */
  confirmSlugChange?: boolean | null;
  notionPageId?: string | null;
  notionUrl?: string | null;
  syncStatus?: ('pending' | 'synced' | 'conflict' | 'error') | null;
  lastSyncedAt?: string | null;
  lastSyncSource?: ('notion' | 'payload') | null;
  syncError?: string | null;
  translationAutoGenerated?: boolean | null;
  migrationKey?: string | null;
  sourceUpdatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  source: string;
  destination: string;
  permanent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'topics';
        value: number | Topic;
      } | null)
    | ({
        relationTo: 'series';
        value: number | Series;
      } | null)
    | ({
        relationTo: 'teachings';
        value: number | Teaching;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  migrationKey?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        social?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  bio?: T;
  profileUrl?: T;
  image?: T;
  migrationKey?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics_select".
 */
export interface TopicsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  migrationKey?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "series_select".
 */
export interface SeriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  kind?: T;
  description?: T;
  image?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonical?: T;
        noIndex?: T;
        socialImage?: T;
      };
  confirmSlugChange?: T;
  translationAutoGenerated?: T;
  migrationKey?: T;
  sourceUpdatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teachings_select".
 */
export interface TeachingsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  body?: T;
  teachingDate?: T;
  series?: T;
  episode?: T;
  author?: T;
  keyVerse?: T;
  topics?: T;
  format?: T;
  durationMinutes?: T;
  youtubeUrl?: T;
  applePodcastsUrl?: T;
  image?: T;
  mediaLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  featured?: T;
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonical?: T;
        noIndex?: T;
        socialImage?: T;
      };
  confirmSlugChange?: T;
  legacy?: T;
  notionPageId?: T;
  notionUrl?: T;
  syncStatus?: T;
  lastSyncedAt?: T;
  lastSyncSource?: T;
  syncError?: T;
  translationAutoGenerated?: T;
  migrationKey?: T;
  sourceUpdatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  body?: T;
  contentDate?: T;
  kind?: T;
  author?: T;
  topics?: T;
  relatedTeachings?: T;
  image?: T;
  featured?: T;
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonical?: T;
        noIndex?: T;
        socialImage?: T;
      };
  confirmSlugChange?: T;
  notionPageId?: T;
  notionUrl?: T;
  syncStatus?: T;
  lastSyncedAt?: T;
  lastSyncSource?: T;
  syncError?: T;
  translationAutoGenerated?: T;
  migrationKey?: T;
  sourceUpdatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  source?: T;
  destination?: T;
  permanent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'series';
          value: number | Series;
        } | null)
      | ({
          relationTo: 'teachings';
          value: number | Teaching;
        } | null)
      | ({
          relationTo: 'resources';
          value: number | Resource;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}