import type {
  CollectionAfterChangeHook,
  CollectionBeforeChangeHook
} from "payload";
import { translateLexical, translateText } from "@/lib/deepl";
import { slugify } from "@/cms/fields/slug";

type TranslatableCollection =
  | "teachings"
  | "resources"
  | "series"
  | "events"
  | "communities";

function hasContent(value: unknown) {
  if (typeof value === "string") return value.trim().length > 0;
  if (!value || typeof value !== "object") return false;

  const root = (value as { root?: { children?: unknown[] } }).root;
  return Array.isArray(root?.children) && root.children.length > 0;
}

/** A save performed by an editor in the English locale protects that translation. */
export const markEnglishTranslationReviewed: CollectionBeforeChangeHook = ({
  data,
  req
}) => {
  if (req.locale !== "en" || req.context?.skipAutoTranslate) return data;
  return { ...data, translationAutoGenerated: false };
};

/**
 * Auto-translation afterChange hook for Payload collections.
 * When a document is saved/published in Spanish ('es'), this hook automatically
 * translates text fields (title, excerpt, body, keyVerse, SEO) into English ('en')
 * and saves them to the English locale of the same document without overwriting manual edits
 * unless explicitly empty or requested.
 */
export const autoTranslateHook = (
  collection: TranslatableCollection
): CollectionAfterChangeHook => async ({ doc, req }) => {
  // English is intentionally disabled until the Spanish Notion catalog is stable.
  if (process.env.ENABLE_ENGLISH_LOCALE !== "true") return doc;
  // Prevent recursion if this update was triggered by auto-translation itself
  if (req.context?.skipAutoTranslate) {
    return doc;
  }

  // Only translate when modifying the Spanish (default) locale
  const currentLocale = req.locale || "es";
  if (currentLocale !== "es") {
    return doc;
  }

  // Drafts and autosaves must never consume translation quota or publish partial copy.
  if (doc._status !== "published") {
    return doc;
  }

  // Only run if DeepL API key is present
  if (!process.env.DEEPL_API_KEY) {
    return doc;
  }

  try {
    // Check what fields exist in English currently to avoid overwriting intentional manual English edits
    const existingEnDoc = (await req.payload.findByID({
      collection: collection as never,
      id: doc.id,
      locale: "en",
      fallbackLocale: false,
      depth: 0,
      overrideAccess: true
    })) as Record<string, unknown> | null;

    const dataToUpdateEn: Record<string, unknown> = {};
    const canReplaceGenerated = doc.translationAutoGenerated === true;
    const shouldTranslate = (value: unknown) =>
      canReplaceGenerated || !hasContent(value);

    // 1. Title / Name
    const esTitle = (doc.title || doc.name) as string | undefined;
    const enTitle = (existingEnDoc?.title || existingEnDoc?.name) as string | undefined;

    if (esTitle && shouldTranslate(enTitle)) {
      const translated = await translateText(esTitle, "EN-US", "ES");
      if (collection === "communities") {
        dataToUpdateEn.name = translated;
      } else {
        dataToUpdateEn.title = translated;
      }

      const enSlug = existingEnDoc?.slug as string | undefined;
      if (shouldTranslate(enSlug)) {
        dataToUpdateEn.slug = slugify(translated);
      }

    }

    // 2. Excerpt / Description
    const esExcerpt = (doc.excerpt || doc.description) as string | undefined;
    const enExcerpt = (existingEnDoc?.excerpt || existingEnDoc?.description) as string | undefined;
    if (esExcerpt && shouldTranslate(enExcerpt)) {
      const translated = await translateText(esExcerpt, "EN-US", "ES");
      if (collection === "communities" || collection === "series") {
        dataToUpdateEn.description = translated;
      } else {
        dataToUpdateEn.excerpt = translated;
      }
    }

    // 3. Body (RichText / Lexical AST)
    if (doc.body && typeof doc.body === "object") {
      // If EN body is missing, translate the Lexical AST
      if (shouldTranslate(existingEnDoc?.body)) {
        const translatedBody = await translateLexical(
          doc.body as Record<string, unknown>,
          "EN-US",
          "ES"
        );
        if (translatedBody) {
          dataToUpdateEn.body = translatedBody;
        }
      }
    }

    // 4. Key Verse (Teachings only)
    if (collection === "teachings" && doc.keyVerse && typeof doc.keyVerse === "string") {
      if (shouldTranslate(existingEnDoc?.keyVerse)) {
        dataToUpdateEn.keyVerse = await translateText(doc.keyVerse, "EN-US", "ES");
      }
    }

    // 5. Community-specific fields
    if (collection === "communities") {
      if (doc.label && typeof doc.label === "string" && shouldTranslate(existingEnDoc?.label)) {
        dataToUpdateEn.label = await translateText(doc.label, "EN-US", "ES");
      }
      if (doc.location && typeof doc.location === "string" && shouldTranslate(existingEnDoc?.location)) {
        dataToUpdateEn.location = await translateText(doc.location, "EN-US", "ES");
      }
      if (doc.schedule && typeof doc.schedule === "string" && shouldTranslate(existingEnDoc?.schedule)) {
        dataToUpdateEn.schedule = await translateText(doc.schedule, "EN-US", "ES");
      }
      if (doc.ctaLabel && typeof doc.ctaLabel === "string" && shouldTranslate(existingEnDoc?.ctaLabel)) {
        dataToUpdateEn.ctaLabel = await translateText(doc.ctaLabel, "EN-US", "ES");
      }
    }

    // 6. Events-specific fields
    if (collection === "events") {
      if (doc.location && typeof doc.location === "string" && shouldTranslate(existingEnDoc?.location)) {
        dataToUpdateEn.location = await translateText(doc.location, "EN-US", "ES");
      }
      if (doc.registrationLabel && typeof doc.registrationLabel === "string" && shouldTranslate(existingEnDoc?.registrationLabel)) {
        dataToUpdateEn.registrationLabel = await translateText(doc.registrationLabel, "EN-US", "ES");
      }
    }

    // 7. SEO fields
    const esSeo = doc.seo as { title?: string; description?: string } | undefined;
    const enSeo = existingEnDoc?.seo as { title?: string; description?: string } | undefined;
    if (esSeo) {
      const seoUpdate: Record<string, unknown> = {};
      if (esSeo.title && shouldTranslate(enSeo?.title)) {
        seoUpdate.title = await translateText(esSeo.title, "EN-US", "ES");
      }
      if (esSeo.description && shouldTranslate(enSeo?.description)) {
        seoUpdate.description = await translateText(esSeo.description, "EN-US", "ES");
      }
      if (Object.keys(seoUpdate).length > 0) {
        dataToUpdateEn.seo = {
          ...(enSeo || {}),
          ...seoUpdate
        };
      }
    }

    // If there is anything to update in English, execute the update
    if (Object.keys(dataToUpdateEn).length > 0) {
      dataToUpdateEn.translationAutoGenerated = true;
      await req.payload.update({
        collection: collection as never,
        id: doc.id,
        locale: "en",
        data: dataToUpdateEn as never,
        context: {
          skipAutoTranslate: true
        },
        overrideAccess: true
      });
    }
  } catch (error) {
    console.error(`Auto-translation hook failed for ${collection} ID ${doc.id}:`, error);
  }

  return doc;
};
