import assert from "node:assert/strict";
import test from "node:test";

import { markEnglishTranslationReviewed } from "../cms/hooks/translate";

test("a manual English save protects the translation from regeneration", () => {
  const result = markEnglishTranslationReviewed({
    data: { title: "Reviewed title", translationAutoGenerated: true },
    req: { locale: "en", context: {} }
  } as never);

  assert.deepEqual(result, {
    title: "Reviewed title",
    translationAutoGenerated: false
  });
});

test("an automatic English save keeps its generated marker", () => {
  const data = { title: "Generated title", translationAutoGenerated: true };
  const result = markEnglishTranslationReviewed({
    data,
    req: { locale: "en", context: { skipAutoTranslate: true } }
  } as never);

  assert.equal(result, data);
});
