import type { Field } from "payload";

export const migrationFields: Field[] = [
  {
    name: "migrationKey",
    type: "text",
    unique: true,
    index: true,
    admin: { hidden: true, disableListColumn: true }
  },
  {
    name: "sourceUpdatedAt",
    type: "date",
    admin: { hidden: true }
  }
];

export const notionSyncFields: Field[] = [
  {
    type: "collapsible",
    label: "Sincronización con Notion",
    admin: { initCollapsed: true },
    fields: [
      {
        type: "row",
        fields: [
          {
            name: "notionPageId",
            type: "text",
            label: "ID de la página en Notion",
            unique: true,
            index: true,
            admin: { width: "50%", readOnly: true }
          },
          {
            name: "notionUrl",
            type: "text",
            label: "Página en Notion",
            admin: { width: "50%", readOnly: true }
          }
        ]
      },
      {
        type: "row",
        fields: [
          {
            name: "syncStatus",
            type: "select",
            label: "Estado",
            options: [
              { label: "Pendiente", value: "pending" },
              { label: "Sincronizado", value: "synced" },
              { label: "Conflicto", value: "conflict" },
              { label: "Error", value: "error" }
            ],
            admin: { width: "33%", readOnly: true }
          },
          {
            name: "lastSyncedAt",
            type: "date",
            label: "Última sincronización",
            admin: { width: "34%", readOnly: true }
          },
          {
            name: "lastSyncSource",
            type: "select",
            label: "Origen del último cambio",
            options: [
              { label: "Notion", value: "notion" },
              { label: "Payload", value: "payload" }
            ],
            admin: { width: "33%", readOnly: true }
          }
        ]
      },
      {
        name: "syncError",
        type: "textarea",
        label: "Detalle del error",
        admin: { readOnly: true, condition: (_, siblingData) => siblingData?.syncStatus === "error" }
      }
    ]
  }
];

export const confirmSlugChangeField: Field = {
  name: "confirmSlugChange",
  type: "checkbox",
  label: "Confirmo que deseo cambiar esta URL publicada",
  defaultValue: false,
  admin: {
    description:
      "Al guardar se creará una redirección permanente desde la URL anterior."
  }
};

export const translationReviewFields: Field[] = [
  {
    name: "translationAutoGenerated",
    type: "checkbox",
    defaultValue: false,
    admin: { hidden: true }
  }
];
