/**
 * Consolidates the legacy Spanish / English teaching documents into Payload's
 * native localized records.
 *
 * Safe defaults:
 *   npm run localization:migrate:dry
 *   npm run localization:migrate -- --write
 *   npm run localization:migrate -- --write --delete-duplicates
 *
 * The delete step is deliberately separate. Run it only after checking both
 * locales in the admin and the generated report.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { getPayload } from "payload";

import config from "../payload.config";
import { translationPairs } from "../lib/content/fallback";

type Id = number | string;
type AnyDoc = Record<string, unknown> & { id: Id };
type Pair = {
  label: string;
  collection: "series" | "teachings";
  es: AnyDoc;
  en: AnyDoc;
};

const write = process.argv.includes("--write");
const deleteDuplicates = process.argv.includes("--delete-duplicates");
const reportPath = resolve(".payload/localization-migration-report.json");

if (deleteDuplicates && !write) {
  throw new Error("--delete-duplicates requires --write.");
}

function relation(value: unknown): AnyDoc | undefined {
  return value && typeof value === "object" && "id" in value
    ? (value as AnyDoc)
    : undefined;
}

function usable(value: unknown) {
  return typeof value === "string" && value.trim().length > 0;
}

function migrationKey(doc: AnyDoc) {
  return typeof doc.migrationKey === "string" ? doc.migrationKey : "";
}

function isEnglishInventory(doc: AnyDoc, collection: "series" | "teaching") {
  return migrationKey(doc).startsWith(`inventory:${collection}:en:`);
}

function indexByRoute(docs: AnyDoc[]) {
  const index = new Map<string, AnyDoc>();
  for (const doc of docs) {
    const series = relation(doc.series);
    if (usable(doc.slug) && usable(series?.slug)) {
      index.set(`${series!.slug}/${doc.slug}`, doc);
    }
  }
  return index;
}

function copyLocalizedFields(collection: Pair["collection"], source: AnyDoc) {
  if (collection === "series") {
    return {
      title: source.title,
      slug: source.slug,
      description: source.description,
      seo: source.seo,
      translationAutoGenerated: false
    };
  }

  return {
    title: source.title,
    slug: source.slug,
    excerpt: source.excerpt,
    body: source.body,
    keyVerse: source.keyVerse,
    seo: source.seo,
    translationAutoGenerated: false
  };
}

async function main() {
  const payload = await getPayload({ config });
  const query = {
    fallbackLocale: false as const,
    depth: 2,
    limit: 1000,
    overrideAccess: true
  };

  const [teachingsResult, seriesResult, resourcesEs, resourcesEn] =
    await Promise.all([
      payload.find({ collection: "teachings", locale: "es", ...query }),
      payload.find({ collection: "series", locale: "es", ...query }),
      payload.find({ collection: "resources", locale: "es", ...query }),
      payload.find({ collection: "resources", locale: "en", ...query })
    ]);

  const allTeachings = teachingsResult.docs as unknown as AnyDoc[];
  const allSeries = seriesResult.docs as unknown as AnyDoc[];
  const esTeachings = indexByRoute(
    allTeachings.filter((doc) => !isEnglishInventory(doc, "teaching"))
  );
  const enTeachings = indexByRoute(
    allTeachings.filter((doc) => isEnglishInventory(doc, "teaching"))
  );
  const esSeries = new Map(
    allSeries
      .filter((doc) => !isEnglishInventory(doc, "series"))
      .filter((doc) => usable(doc.slug) && usable(doc.title))
      .map((doc) => [String(doc.slug), doc])
  );
  const enSeries = new Map(
    allSeries
      .filter((doc) => isEnglishInventory(doc, "series"))
      .filter((doc) => usable(doc.slug) && usable(doc.title))
      .map((doc) => [String(doc.slug), doc])
  );

  const pairs: Pair[] = [];
  const missing: string[] = [];
  const seenSeries = new Set<string>();

  for (const [label, target] of Object.entries(translationPairs)) {
    const esTeaching = esTeachings.get(`${target.es.collection}/${target.es.slug}`);
    const enTeaching = enTeachings.get(`${target.en.collection}/${target.en.slug}`);
    if (!esTeaching || !enTeaching) {
      missing.push(
        `${label}: ${target.es.collection}/${target.es.slug} <> ${target.en.collection}/${target.en.slug}`
      );
      continue;
    }

    pairs.push({ label, collection: "teachings", es: esTeaching, en: enTeaching });

    const seriesKey = `${target.es.collection}<>${target.en.collection}`;
    if (!seenSeries.has(seriesKey)) {
      const es = esSeries.get(target.es.collection);
      const en = enSeries.get(target.en.collection);
      if (es && en) {
        pairs.push({ label: `serie:${seriesKey}`, collection: "series", es, en });
        seenSeries.add(seriesKey);
      }
    }
  }

  const report = {
    mode: write ? (deleteDuplicates ? "write-and-delete" : "write") : "dry-run",
    generatedAt: new Date().toISOString(),
    discovered: {
      teachingsEs: esTeachings.size,
      teachingsEn: enTeachings.size,
      seriesEs: esSeries.size,
      seriesEn: enSeries.size,
      resourcesEs: (resourcesEs.docs as unknown as AnyDoc[]).filter((doc) => usable(doc.title)).length,
      resourcesEn: (resourcesEn.docs as unknown as AnyDoc[]).filter((doc) => usable(doc.title)).length
    },
    plannedPairs: pairs.map((pair) => ({
      collection: pair.collection,
      label: pair.label,
      targetId: pair.es.id,
      duplicateId: pair.en.id
    })),
    missing,
    migrated: [] as string[],
    verified: [] as string[],
    deleted: [] as string[],
    warnings: [] as string[]
  };

  if (report.discovered.resourcesEn > 0) {
    report.warnings.push(
      "Hay artículos en inglés, pero el inventario actual no define pares inequívocos. No se modificaron; agrega un mapa de pares antes de migrarlos."
    );
  }

  if (write) {
    for (const pair of pairs) {
      await payload.update({
        collection: pair.collection,
        id: pair.es.id,
        locale: "en",
        data: copyLocalizedFields(pair.collection, pair.en) as never,
        context: {
          skipAutoTranslate: true,
          skipNotionSync: true,
          skipSlugGuard: true
        },
        overrideAccess: true
      });
      report.migrated.push(`${pair.collection}:${pair.label}`);

      const verified = (await payload.findByID({
        collection: pair.collection,
        id: pair.es.id,
        locale: "en",
        fallbackLocale: false,
        depth: 0,
        overrideAccess: true
      })) as unknown as AnyDoc;
      const verifiedTitle = verified.title;
      const expectedTitle = pair.en.title;
      if (!usable(verifiedTitle) || verifiedTitle !== expectedTitle) {
        throw new Error(`Verification failed for ${pair.collection}:${pair.label}`);
      }
      report.verified.push(`${pair.collection}:${pair.label}`);
    }

    if (deleteDuplicates) {
      const contentDuplicates = pairs.filter((pair) => pair.collection !== "series");
      const seriesDuplicates = pairs.filter((pair) => pair.collection === "series");
      for (const pair of [...contentDuplicates, ...seriesDuplicates]) {
        if (pair.es.id === pair.en.id) continue;
        await payload.delete({
          collection: pair.collection,
          id: pair.en.id,
          overrideAccess: true
        });
        report.deleted.push(`${pair.collection}:${pair.en.id}`);
      }
    }
  }

  await mkdir(resolve(".payload"), { recursive: true });
  await writeFile(reportPath, `${JSON.stringify(report, null, 2)}\n`, "utf8");
  console.log(JSON.stringify({ reportPath, ...report }, null, 2));
  process.exit(0);
}

void main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
